name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # 每天 00:00 UTC 自动运行
  workflow_dispatch:       # 允许手动触发

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: CheRongtian
          outputs: dist/snake.svg
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

